### ISSUE TITLE
Upload of big package files

### ISSUE THREAD

**Issue by NMonst4** [totaljs/superadmin#12]
Hi,

i get a no message error output from superadmin when i upload a 80 MB package file. Where is the limit of this files defined? 

A nice feature would be a config where i limit the size of packages and a error of package is to big.

It´s a very nice app and I am so happy with this hosting solution.

Best reagrds,

NMonst4

**Comment by petersirka** [comment]
Hi @NMonst4,
try to increase upload limit here:
<https://github.com/totaljs/superadmin/blob/master/controllers/api.js#L17>

Thank you.

**Comment by NMonst4** [comment]
Thank you. 👍 But i solved it with removing the .git direcotry from my folder to create a smaler .package
