### ISSUE TITLE
SuperAdmin counter stay 0

### ISSUE THREAD

**Issue by hepr** [totaljs/superadmin#14]
Hi Peter,

I don't know if it's normal but all my counter on top stay always 0.
And I don't have the same interface like you.
I add screenshot below

Thanks 

Herve

![1609142351tjjr7y](https://cloud.githubusercontent.com/assets/1666015/20215912/f608cd40-a817-11e6-8f18-cde30cb1487d.png)
![screenshot - 11112016 - 14 02 46](https://cloud.githubusercontent.com/assets/1666015/20215915/fb0dcc1e-a817-11e6-84a4-533821b511b5.png)

**Comment by petersirka** [comment]
@hepr you have to add a monitor module into your websites and then just register its relative URL address like this (the picture below is from `Edit application` form:

![image](https://cloud.githubusercontent.com/assets/2414252/20216006/4eaed2aa-a818-11e6-87c4-002a000f7ae3.png)

Monitor module: https://github.com/totaljs/modules/tree/master/Miscellaneous/monitor

**Comment by hepr** [comment]
Hi Peter,

I had $monitor on all site.
I'm using cms package. Is there $monitor ?
Because my counter stay 0 :-(

Thanks

Herve

![screenshot - 14112016 - 09 08 33](https://cloud.githubusercontent.com/assets/1666015/20257476/20ea942e-aa4a-11e6-8817-d5c3d4b2cdb0.png)

**Comment by petersirka** [comment]
@hepr create `/dependencies` file with this content:

```html
module					: https://modules.totaljs.com/latest/monitor.js --> {"url":"/$monitor/"}
module					: https://modules.totaljs.com/latest/reqstats.js
```

Then restart apps.

**Comment by petersirka** [comment]
Any news?

**Comment by hepr** [comment]
All is ok 
Thanks :-)
