### ISSUE TITLE
overwritten log files

### ISSUE THREAD

**Issue by patrickschoeberlein** [totaljs/superadmin#16]
Hi Peter,

i use superadmin for a few projects. Sometimes my servers crash... so i have to restart them (via superadmin). 

However, after restarting the old logfile is overwritten, so i cannot see what went wrong before restarting the server. Is it possible for superadmin to keep the old logfile? 

If not - it would surely be a good new feature 😄

**Comment by petersirka** [comment]
Hi @patrickschoeberlein, yes of course I'll add it today. But `server crash` is really interesting, do you have a free memory or free disk space? I provide more than 40 apps on the one server and without any problem (yet).

**Comment by patrickschoeberlein** [comment]
no, there is no special memory management for releasing memory. I think i have a memory leak somewhere and after ~2 weeks it causes my nodejs-application to fail :( But I am not 100% sure about that. Actually, the virtual server that i use for hosting is out of memory quite often - but that does NOT cause the nodejs-application to crash, it only gets a bit slower.

**Comment by petersirka** [comment]
Hi @patrickschoeberlein, I forgot on you but .... I have added a backup of logs.
Here is a latest stable version: <https://github.com/totaljs/superadmin/tree/v5.0.0> and I'll publish next week a new version.

Thank you!

**Comment by petersirka** [comment]
Please give me a feedback about crashing...
