### ISSUE TITLE
Remove superadmin

### ISSUE THREAD

**Issue by timonsk** [totaljs/superadmin#17]
Hi all,
Unfortunately, I could not found solution how to delete superadmin from my Ubuntu Server 16 correctly.
So could you please tell me how to do that?
Thanks!

**Comment by molda** [comment]
Hi @timonsk
Here's what to do:
- stop all apps in SuperAdmin
- kill SuperAdmin using this command `kill -9 $(lsof -i :9999 | grep "total" | awk {'print $2'}) > /dev/null`
- to replace nginx.conf with backed up file use this command `cp /etc/nginx/nginx.conf.backup /etc/nginx/nginx.conf`
- reload nginx `service nginx reload` and/or just stop it `service nginx stop`
- if you added a cron job to start apps at system startup then remove this line @reboot /bin/bash /www/superadmin/run.sh from crontab using `crontab -e` command
- remove /www/ folder, this will remove all ssl certificates, nginx conf files, all applications, etc.
- to remove node.js run `apt-get remove -y nodejs`
- to remove nginx run `apt-get remove -y nginx`
- to remove graphicsmagick run `apt-get remove -y graphicsmagick`

That should be all you need.
Hope it helps.

**Comment by timonsk** [comment]
Than you @molda !
It helps! One more, could you please add this explanation for future generations to readme.md?
Thank's!

**Comment by molda** [comment]
Cool. I will add it, i already wanted to do it i just forgot :)

Thanks.

**Comment by petersirka** [comment]
I have added it <https://github.com/totaljs/superadmin/tree/v5.0.0#uninstall-superadmin>.
