### ISSUE TITLE
rpm based installation script ?

### ISSUE THREAD

**Issue by kfirufk** [totaljs/superadmin#19]
Hello.

I want to install superadmin in order to replace pm2 on centos.
is there an rpm based installation script? 
I'm really excited about this project, if there isn't.. i'll create one.
just want to know if anyone started the progress or is there any basic instructions on how to install
this on non-debian linux distro.

thank you!

**Comment by petersirka** [comment]
Hi @kfirufk,
here is an installation script <https://github.com/totaljs/superadmin/blob/master/install.sh> but we use Ubuntu Server. Maybe it will work when you keep SuperAdmin requirements.

Give me a feedback.
Thank you!

**Comment by petersirka** [comment]
BTW: Is there a problem to use __Ubuntu Server__?

**Comment by kfirufk** [comment]
Unfortunately I don't have ubuntu servers to test it on. We use gentoo, centos, coreos and an amazon linux distribution based on redhat

**Comment by petersirka** [comment]
Try to modify install script and I can help you with another things.

__SuperAdmin uses these commands/apps__:

- bash
- lsb_release
- lsof
- ps
- netstat
- ifconfig
- uptime
- grep
- awk
- wc
- du
- cat
- free
- df
- tail
- last
- tar
- cp
- mkdir
- npm

Give me a feedback.
