### ISSUE TITLE
superadmin domain?

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/superadmin#20]
Can superadmin work without a domain?

**Comment by petersirka** [comment]
Yes, but I recommend to create a fake domain with help of hosts.

**Comment by adrianrey05** [comment]
After the installation how can I access from the public IP?

**Comment by molda** [comment]
@adrianrey05 Hi, the way we access superadmin is that we set server_name in /www/nginx/superadmin.conf file to some fake domain as suggested by @petersirka 
To get this working:
- update the server_name in superadmin.conf on your server -> `server_name superadmin.fake`
- update your hosts file in your PC by adding this "<server-ip-address> superadmin.fake" e.g. `1.2.3.4 superadmin.fake`

Now open your browser and type http://superadmin.fake

That's it.
