### ISSUE TITLE
on hover popup for monitor?

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/superadmin#21]
Hello, set up a page with the monitor module from superadmin.
When I go to the url domain/$monitor it shows the statistics.
But it does not show me the popup as it appears on the superadmin landing 
It does not show any errors from the console.

thank you very much for your help.

(https://www.totaljs.com/superadmin).
![image](https://cloud.githubusercontent.com/assets/5314570/21335445/c0277200-c63d-11e6-9136-b195c21868aa.png)

my app
![image](https://cloud.githubusercontent.com/assets/5314570/21335476/ed04b59e-c63d-11e6-9c38-98f82cac64f0.png)

**Comment by petersirka** [comment]
Hi @adrianrey05,
try to refresh website and move your cursor to your website... still nothing?

**Comment by adrianrey05** [comment]
Before lifting the issue I did many times, also cleared all navigation data.
Today just started working... :confused: 
A thousand apologies and thanks.

**Comment by petersirka** [comment]
:-D no problem! Great 👍
