### ISSUE TITLE
After upgrade problem with ssl certs

### ISSUE THREAD

**Issue by NMonst4** [totaljs/superadmin#22]
Hi,

after i upgraded superdamin from 4 to 5 i get strange ssl renew error. I cant renew the cert from superadmin backend 

Error:
```
jquery.min.js:4 POST http://SERVERNAME/api/apps/ 408 (Request Timeout)
```

and from command line with "bash ssl.sh WEBADDRESS --renew"

i get 

Error
```
:Verify error:Invalid response from http://
```

ok i break it down and i get a succesfull renew if i add a "Listen 80;" to nginx.conf for the app in "/www/nginx/APPNAME.conf"

What´s wrong with my upgrade? Anything else is running fine.

**Comment by petersirka** [comment]
Hi,
v5 has a new NGINX configuration file. Please backup:

- `/www/nginx/`
- `/www/superadmin/`
- and try to run `Reconfigure all` option

![image](https://cloud.githubusercontent.com/assets/2414252/21844710/f3f0db3a-d7ef-11e6-9493-134418a3faa1.png)

I'll look into it If the problem will persist.

Thank you!

**Comment by NMonst4** [comment]
ok i thing i get my mistake. The error was an missing `npm update ` and then `bash run.sh` after upgrade. Strange but now all is working fine. Thanks for your quick reaction. <3
