### ISSUE TITLE
node arguments

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/superadmin#23]
Hi,
How can I add node arguments to an application?
example:
node --harmony-async-await release.js

**Comment by petersirka** [comment]
This is not possible, but ...

- open `/definitions/superadmin.js`
- try to find `var options = ['--nouse-idle-notification', '--expose-gc', '--max_inlined_source_size=1200'];`
- add your argument
- restart app

👍

**Comment by adrianrey05** [comment]
its work!
thank you @petersirka
