### ISSUE TITLE
nginx: not found

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/superadmin#24]
Hi, 
When I want to renew the certificates give this error.

 Error: Command failed: nginx -t /bin/sh: 1: nginx: not found

Thanks

**Comment by molda** [comment]
Hi @adrianrey05 
Do you have nginx properly installed?
Try to run following command in terminal
`nginx -v`
If it doesn't show something like `nginx version: nginx/1.10.0 (Ubuntu)` it means it's not installed properly.
Try to reinstall it using following as root user `apt-get install -y nginx` and try again.

**Comment by adrianrey05** [comment]
Hi @molda ,
yes, nginx is properly installer.
```terminal
nginx version: nginx/1.10.0 (Ubuntu)
```
i use this for the installation

```terminal
sudo wget https://cdn.totaljs.com/superadmin.sh && bash superadmin.sh
````

**Comment by molda** [comment]
Hi i'm sorry i totally forgot about your issue. 
I just run into the same problem and had to change all `Exec('nginx...` in ./definitions/superadmin.js to `Exec('/usr/sbin/nginx....` 

I'm sorry again for late reply.

Fix will be added soon.

**Comment by adrianrey05** [comment]
thanks @molda its work now!!
