### ISSUE TITLE
nginx: not found

### ISSUE THREAD

**Issue by ozjd** [totaljs/superadmin#27]
Similar to (resolved) issue #24 - nginx is not found.

Steps to reproduce:
1. Install Ubuntu-Server (latest LTS).
2. Use SuperAdmin install script
- Everything now works -
3. Reboot.
- Now everything is broken -
** Testing nginx will fail
** Creating a new website will fail
** etc.

The issue appears to be caused by the path for root having only been set to '**/usr/bin:/bin**' at the time of calling run.sh, when a `which nginx` shows it's located in '**/usr/sbin/nginx**'.

For now, I've prefixed line 3 in /www/superadmin/run.sh with `PATH=$PATH:/usr/sbin` which seems to solve the issue (rather than hardcoding the absolute path in ./definitions/superadmin.js  as @molda suggested). It would be preferable to use the result from `which nginx` for setting this path.

**Comment by petersirka** [comment]
I'll fix it. __Premium SuperAdmin__ has this fix.
