### ISSUE TITLE
superadmin couldn't start!

### ISSUE THREAD

**Issue by Pourya8366** [totaljs/superadmin#32]
Hi!
after i try to start superadmin with  `bash run..sh` command in `/www/superadmin/` directory, this message shows up:
`kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`
the OS is Ubuntu 16.04

**Comment by molda** [comment]
Hi you can ignore the error. SuperAdmin should be running. The reason for the error is that there was no process running so the kill command failed. I'll try to improve the script to avoid this message.

**Comment by Pourya8366** [comment]
oh OK!
so how can i lunch the web console?

**Comment by molda** [comment]
The app should be accessible at localhost on port 80 or if the app is running on remote server then on the server's IP.

**Comment by petersirka** [comment]
Try to check if the superadmin works:

```bash
lsof -i :9999
```

If it runs then the problem can be in nginx superadmin config. You need to debug it step-by-step or we can help you within Total.js support.

Thank you!

**Comment by molda** [comment]
@Pourya8366 sorry the default port is actualy 9999 as Peter mentioned. I totally forgot about that since i used to run it on port 80.

Yout can also try bellow command to see all total.js apps

`$ ps -aux | grep total`

**Comment by Pourya8366** [comment]
I check the running state of superadmin with `lsof -i :9999` and it's not running!
so where the problem might be?

**Comment by petersirka** [comment]
Please open terminal:

```bash
$ cd /www/superadmin/
$ /usr/bin/node --nouse-idle-notification --expose-gc /www/superadmin/release.js 9999
```

Show me the log.

**Comment by Pourya8366** [comment]
Suddenly when i start the system today it's working and i don't know why! 😄 
so thanks a lot!
