### ISSUE TITLE
Custom NGINX configuration error 

### ISSUE THREAD

**Issue by TeoDoe777** [totaljs/superadmin#38]
I get an error when saving
> Error: Command failed: /usr/sbin/nginx -t nginx: [emerg] "server" directive is not allowed here in /www/nginx/test123_com.conf:13 nginx: configuration file /etc/nginx/nginx.conf test failed

config itself

```
server {
     listen 80;
     server_name mydomainname.com;
     location / {
         proxy_set_header X-Real-IP $ remote_addr;
         proxy_set_header Host $ http_host;
         proxy_pass http://127.0.0.1:2368;
     }
}
```

**Comment by petersirka** [comment]
Which version of Nginx do you use? My config is similar and it works correctly:

```lua
server {
	listen         80;
	server_name    www.totaljs.com;
	server_name    totaljs.com;

	location ~ "^/\.well-known/acme-challenge/([-_a-zA-Z0-9]+)$" {
		allow all;
		default_type "text/plain";
		return 200 "??????";
	}

	location ~ / {
		return 301 https://www.totaljs.com$request_uri;
	}
}
server {
	listen         443 ssl;
	server_name    totaljs.com;

	ssl_certificate ????;
	ssl_certificate_key ????;
	ssl_trusted_certificate ????;
	ssl_session_timeout 5m;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_session_cache shared:SSL:10m;
	ssl_protocols SSLv3 TLSv1.2 TLSv1.1 SSLv2;
	ssl_prefer_server_ciphers on;
	ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

	location ~ / {
		return 301 https://www.totaljs.com$request_uri;
	}
}
```

My version of NGINX: `v1.10.3`

**Comment by TeoDoe777** [comment]
This error occurs when setting up the project in the "Custom NGINX configuration" field, your configuration set, also an error
Version nginx / 1.10.3. Help solve the problem. Thank you in advance!

**Comment by TeoDoe777** [comment]
I installed it on a local machine, everything is the same, for any config it writes an error almost the same

**Comment by molda** [comment]
What did you put into the "Custom NGINX configuration" field?

**Comment by TeoDoe777** [comment]
```
server {
     listen 80;
     server_name mydomainname.com;
     location / {
         proxy_set_header X-Real-IP $ remote_addr;
         proxy_set_header Host $ http_host;
         proxy_pass http://127.0.0.1:2368;
     }
}
```

**Comment by molda** [comment]
That is wrong. What are you trying to achieve?

This would create a nginx conf like this

    server {
        ...
        server {
             ....
        }
    }

And that's incorrect. Server directive cannot be nested inside another server directive.

This is the line your code gets inserted into https://github.com/totaljs/superadmin/blob/master/databases/website.conf#L31

**Comment by TeoDoe777** [comment]
I want to redirect the site to the node from port 8000 to port 80

**Comment by TeoDoe777** [comment]
so how then do I make the config?
can be an example, I do not understand

**Comment by molda** [comment]
Nginx listens on port 80 and redirects the request based on hostname. In the SuperAdmin you only set the domain name and that's it. SuperAdmin will create the nginx config with the proxy_pass property set to correct port. You don't need to do anything.

**Comment by TeoDoe777** [comment]
I have already done this, in the end, port 80 is not revoked ... although if you go to the site with port 8000 then everything is ok

**Comment by TeoDoe777** [comment]
Another question, is it possible to make another administrator account?

**Comment by molda** [comment]
No, it isn't.
Maybe in the next version.

**Comment by petersirka** [comment]
@molda thank you, I was out. @TeoDoe777 admin another account is currently not possible to add. We  want to update SuperAdmin this year.
