### ISSUE TITLE
nginx: [error] invalid PID number

### ISSUE THREAD

**Issue by samy-senouci** [totaljs/superadmin#41]
Im getting this error after trying to create a new application in superadmin on a fresh installation in a digitalocean droplet:
Error: Command failed: /usr/sbin/nginx -s reload nginx: [warn] "ssl_stapling" ignored, no OCSP responder URL in the certificate "/www/ssl/superadmin.csr" nginx: [error] invalid PID number "" in "/var/run/nginx.pid"

![Screenshot](https://user-images.githubusercontent.com/68273355/114467222-7b173f00-9be1-11eb-980e-3dc192eb1a60.jpg)

**Comment by petersirka** [comment]
Hi Samy, you need to check Nginx. SuperAdmin depends on Nginx and evidently your Nginx doesn't work.

- open terminal: `service nginx status`
- if the Nginx responds without error, try to restart superadmin: `cd /www/superadmin/ && bash run.sh`
- if the terminal responds with error, you need solve a problem with Nginx.

**Comment by samy-senouci** [comment]
Hi, I've checked the Nginx status and it's working fine, and I restarted superadmin, but still getting the same error

**Comment by petersirka** [comment]
Then try to check if the SuperAdmin is running under `root` or if the user is the same as you test `nginx`

**Comment by samy-senouci** [comment]
yes, superadmin is running under the `root` user, same with Nginx.
